version: '3.8'

services:
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vaca-muerta-observability
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0
